name: Blueprint generator for current commit
on:
  push:
    branches:
      - devel
      - main

jobs:

  build-fbpconvert-executable:
    runs-on: ubuntu-latest

    steps:
      - name: 'clone repository'
        run: git clone https://github.com/cruzerngz/fbpconvert.git .

      - name: 'build release'
        run: |
          cargo build --release
      - name: 'upload executable artifact'
        uses: actions/upload-artifact@v3
        with:
          name: fbpconvert
          path: ./target/release/fbpconvert

  generate-blueprint-string:
    runs-on: ubuntu-latest
    needs: Build-fbpconvert-executable

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: fbpconvert

    - name: 'convert to blueprint string'
      run: |
        chmod +x ./fbpconvert
        ./fbpconvert export file ./hex_cells -o blueprint.txt

    - name: 'upload blueprint book'
      uses: actions/upload-artifact@v3
      with:
        name: blueprint_book.txt
        path: ./blueprint.txt
